version: "2"
networks:
  scirocco_mongo:
services:
  scirocco_server:
    restart: always
    working_dir: /usr/src/app
    environment:
      - SCIROCCO_ENV
      - SCIROCCO_PORT
      - SCIROCCO_MONGO_URL
      - SCIROCCO_MASTER_TOKEN
      - SCIROCCO_MAX_KB_SIZE_RAW
      - SCIROCCO_MAX_KB_SIZE_TEXT
      - SCIROCCO_MAX_KB_SIZE_JSON
      - SCIROCCO_MAX_GET_ALL_MESSAGES

    user: app
    build: node
    image: scirocco-server
    ports:
      - "${SCIROCCO_DOCKER_HOST_PORT}:${SCIROCCO_PORT}"
    networks:
      scirocco_mongo:
        aliases:
          - "scirocco-server"
    depends_on:
      - "scirocco_db"
  scirocco_db:
    restart: always
    build: mongo
    image: scirocco-mongo
    expose:
      - "27017"
    networks:
      scirocco_mongo:
        aliases:
          - "scirocco-db"
    command: "--storageEngine wiredTiger"






  